# tests that all packages can be loaded
library(ROAuth)
library(streamR)
library(ggplot2)
library(stringr)
library(Rfacebook)
library(devtools)
library(quanteda)
library(igraph)
library(rvest)
library(httr)
library(yaml)
library(netdemR)
library(topicmodels)
